---
- hosts: localhost

  tasks:
  - name: Fetch Instance Info
    os_server_info:
      cloud: openstack
      region_name: regionOne
    register: r_os_servers

  - name: Add host
    add_host:
      ansible_ssh_private_key_file: ~/.ssh/ansible_ssh_key
      ansible_ssh_user: cloud-user
      host: "{{ item.accessIPv4 }}"
      group:
        - "{{ item.metadata.group }}"
    loop: "{{ r_os_servers.openstack_servers }}"


  - debug: var=groups

- name: ping
  hosts: app_servers
  tasks:
    - ping:
