---
- name: Deploy, configure, and populate Postgres 10
  hosts: database_servers
  become: true
  gather_facts: false
  tags:
    - database_servers
  
  vars_files:
    - "group_vars/database_servers.yml"

  roles:

    - postgres
